eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      enabled: false
  application:
    name: catalog-service
    cloud:
      config:
        import-check:
          enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.1.165.13:8080/realms/myrealm

hystrix.dashboard.proxy-stream-allow-list: '*'
app:
  greeting: hello


db:
 connection: 192.167.168.222:4444
 table: test

#management.endpoints.web.exposure.include: hystrix.stream
management.endpoints.web.exposure.include: '*'

#spring.profiles.active: test

server:
  port: 8181
