spring:
  application:
    name: api-gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path= /catalog/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://10.1.165.13:8080/realms/myrealm
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak
            client-id: spring-gateway-client
            client-secret: TNIDwPASDq0eBZPwUC50IzwXHvFuKpUp
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9090